FROM energy-service-generics:latest-service-pandas

RUN pip install pvlib scipy
COPY ./service/ /source/service/

WORKDIR /source/service/
ENTRYPOINT [ "celery" ]
CMD [ "--app", "worker", "worker", "--loglevel=INFO" ]
